apiVersion: v1
kind: ConfigMap
metadata:
  name: logdna-rsyslog-config
data:
  logdna-url: logs.logdna.com
  rsyslog-config: |+
    # Host TCP server and http forwarder
    module(load="imtcp")
    module(load="imudp")
    module(load="omhttp")
    $InputTCPServerRun 6514
    $UDPServerRun 6514

    # Transform syslog format to LogDNA format
    $template logdna_rsyslog,"{\"lines\":[{\"hostname\":\"%HOSTNAME%\",\"app\":\"%APP-NAME%\",\"level\":\"%SYSLOGSEVERITY-TEXT%\",\"timestamp\":\"%timegenerated:::date-rfc3339%\",\"line\":\"%msg:::json%\"}]}"

    # HTTPS forwarding configuration
    action(type="omhttp" server="LDLOGHOST" serverport="443" restpath="logs/ingest?hostname=logdna-rsyslog" dynRestPath="off" usehttps="on" template="logdna_rsyslog" uid="LOGDNA_AGENT_KEY")
